consumes:
- application/json
definitions:
  Event:
    properties:
      category:
        $ref: '#/definitions/EventCategory'
      description:
        type: string
        x-go-name: Description
      event_id:
        type: string
        x-go-name: EventID
      host_time:
        format: int64
        type: integer
        x-go-name: HostTime
      location:
        $ref: '#/definitions/GeographyPoints'
      name:
        type: string
        x-go-name: Name
      start_time:
        format: int64
        type: integer
        x-go-name: StartTime
    type: object
    x-go-package: github.com/Sayitsocial/Sayitsocial_go/pkg/models/event
  EventAttendeeBridge:
    properties:
      event:
        $ref: '#/definitions/Event'
      generated_id:
        type: string
        x-go-name: GeneratedID
      volunteer:
        $ref: '#/definitions/VolData'
    type: object
    x-go-package: github.com/Sayitsocial/Sayitsocial_go/pkg/models/event/bridge/eventattendee
  EventCategory:
    properties:
      generated_id:
        format: int64
        type: integer
        x-go-name: GeneratedID
      name:
        type: string
        x-go-name: Name
    type: object
    x-go-package: github.com/Sayitsocial/Sayitsocial_go/pkg/models/event/categories
  EventHostBridge:
    properties:
      event:
        $ref: '#/definitions/Event'
      generated_id:
        type: string
        x-go-name: GeneratedID
      organisation:
        $ref: '#/definitions/OrgData'
      volunteer:
        $ref: '#/definitions/VolData'
    type: object
    x-go-package: github.com/Sayitsocial/Sayitsocial_go/pkg/models/event/bridge/eventhost
  GeographyPoints:
    description: |-
      GeographyPoints is a struct that holds longitude, latitude of a location and optionally radius
      Radius can be specified to initiate a search of other points in radius from specified coordinates
    properties:
      latitude:
        format: double
        type: number
        x-go-name: Latitude
      longitude:
        format: double
        type: number
        x-go-name: Longitude
    type: object
    x-go-package: github.com/Sayitsocial/Sayitsocial_go/pkg/models
  OrgData:
    properties:
      achievements:
        type: string
        x-go-name: Achievements
      contact_email:
        type: string
        x-go-name: ContactEmail
      contact_phone:
        type: string
        x-go-name: ContactPhone
      desc:
        type: string
        x-go-name: Desc
      display_name:
        type: string
        x-go-name: DisplayName
      locality:
        type: string
        x-go-name: Locality
      organisation_id:
        type: string
        x-go-name: OrganisationID
      owner:
        type: string
        x-go-name: Owner
      registration_no:
        type: string
        x-go-name: RegistrationNo
      type_of_org:
        format: int64
        type: integer
        x-go-name: TypeOfOrg
    type: object
    x-go-package: github.com/Sayitsocial/Sayitsocial_go/pkg/models/orgdata
  VolData:
    properties:
      bio:
        type: string
        x-go-name: Bio
      contact_email:
        type: string
        x-go-name: ContactEmail
      contact_phone:
        type: string
        x-go-name: ContactPhone
      display_name:
        type: string
        x-go-name: DisplayName
      joined:
        format: int64
        type: integer
        x-go-name: Joined
      volunteer_id:
        type: string
        x-go-name: VolunteerID
    type: object
    x-go-package: github.com/Sayitsocial/Sayitsocial_go/pkg/models/voldata
host: sayitsocial-dev.ddns.net:8000
info:
  description: Documentation of SayItSocialAPI.
  title: classification SayItSocial.
  version: 1.0.0
paths:
  /api/event/attendee:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: |-
        This will show attendees of an event.
        Atleast one param is required
      operationId: getEventAttendee
      parameters:
      - description: Generated ID
        in: query
        name: generated_id
        type: string
        x-go-name: GeneratedID
      - description: ID of host of event (user)
        in: query
        name: volunteer_id
        type: string
        x-go-name: VolunteerID
      - description: ID of event
        in: query
        name: event_id
        type: string
        x-go-name: EventID
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/eventAttendeeResponse'
      schemes:
      - http
      security:
      - JWTAuth:
        - '[]'
      summary: Get attendees of event
      tags:
      - event
  /api/event/create:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: This will show create a new event.
      operationId: createEvent
      parameters:
      - description: ID of host of event (org)
        in: query
        name: organisation_id
        type: string
        x-go-name: OrganisationID
      - description: ID of host of event (user)
        in: query
        name: volunteer_id
        type: string
        x-go-name: VolunteerID
      - description: Name of event
        in: query
        name: name
        type: string
        x-go-name: Name
      - description: Name of event
        in: query
        name: description
        type: string
        x-go-name: Description
      - description: Start time of event [unix timestamp]
        format: int64
        in: query
        name: start_time
        type: integer
        x-go-name: StartTime
      - description: Type of category [Refer to event_category]
        format: int64
        in: query
        name: category
        type: integer
        x-go-name: Category
      - description: Location in [Longitude, Latitude]
        in: query
        items:
          format: double
          type: number
        maxItems: 2
        minItems: 2
        name: location
        type: array
        x-go-name: Location
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/successResponse'
      schemes:
      - http
      summary: Create a new event
      tags:
      - event
  /api/event/get:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: |2-

        This will show details of event
        Atleast one param is required
      operationId: getEvent
      parameters:
      - description: Event id of event
        in: query
        name: event_id
        type: string
        x-go-name: EventID
      - description: Name of event
        in: query
        name: name
        type: string
        x-go-name: Name
      - description: Start time of event [unix timestamp]
        format: int64
        in: query
        name: start_time
        type: integer
        x-go-name: StartTime
      - description: Host time of event [unix timestamp]
        format: int64
        in: query
        name: host_time
        type: integer
        x-go-name: HostTime
      - description: Type of category [Refer to event_category]
        format: int64
        in: query
        name: category
        type: integer
        x-go-name: Category
      - description: Location in [Longitude, Latitude, Radius]
        in: query
        items:
          format: double
          type: number
        maxItems: 3
        minItems: 3
        name: location
        type: array
        x-go-name: Location
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/eventResponse'
      schemes:
      - http
      summary: Get details of event
      tags:
      - event
  /api/event/host:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: |-
        This will show hosts of an event.
        Atleast one param is required
      operationId: getEventHost
      parameters:
      - description: Generated ID
        in: query
        name: generated_id
        type: string
        x-go-name: GeneratedID
      - description: ID of host of event (org)
        in: query
        name: organisation_id
        type: string
        x-go-name: OrganisationID
      - description: ID of host of event (user)
        in: query
        name: volunteer_id
        type: string
        x-go-name: VolunteerID
      - description: ID of event
        in: query
        name: event_id
        type: string
        x-go-name: EventID
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/eventHostResponse'
      schemes:
      - http
      summary: Get hosts of event
      tags:
      - event
  /api/org/create:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: This will show create a new organisation.
      operationId: createOrganisation
      parameters:
      - description: Email of Organisation
        in: query
        name: email
        required: true
        type: string
        x-go-name: Email
      - description: Password of user
        in: query
        name: password
        required: true
        type: string
        x-go-name: Password
      - description: Name of Organisation
        in: query
        name: org_name
        required: true
        type: string
        x-go-name: OrgName
      - description: Type of Organisation
        format: int64
        in: query
        name: org_type
        required: true
        type: integer
        x-go-name: TypeOfOrg
      - description: Locality of Organisation
        in: query
        name: locality
        required: true
        type: string
        x-go-name: Locality
      - description: Owner of Organisation
        in: query
        name: owner
        required: true
        type: string
        x-go-name: Owner
      - description: Registration Number of organisation according to ngodarpan if applicable
        in: query
        name: reg_no
        type: string
        x-go-name: RegistrationNo
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/successResponse'
      schemes:
      - http
      summary: Create a new organisation
      tags:
      - organisation
  /api/org/get:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: |-
        This will details of an organisation.
        Atleast one param is required
      operationId: getOrganisation
      parameters:
      - description: Organisation ID
        in: query
        name: organisation_id
        type: string
        x-go-name: OrganisationID
      - description: Name of organisation
        in: query
        name: display_name
        type: string
        x-go-name: DisplayName
      - description: Owner of organisation
        in: query
        name: owner
        type: string
        x-go-name: Owner
      - description: Type of organisation
        format: int64
        in: query
        name: type_of_org
        type: integer
        x-go-name: TypeOfOrg
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/orgResponse'
      schemes:
      - http
      summary: Get details of an organisation
      tags:
      - organisation
  /api/vol/create:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: This will create a new volunteer.
      operationId: createVolunteer
      parameters:
      - description: First name of user
        in: query
        name: first_name
        required: true
        type: string
        x-go-name: FirstName
      - description: Last name of user
        in: query
        name: last_name
        required: true
        type: string
        x-go-name: LastName
      - description: Email of user
        in: query
        name: email
        required: true
        type: string
        x-go-name: Email
      - description: Password of user
        in: query
        name: password
        required: true
        type: string
        x-go-name: Password
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/successResponse'
      schemes:
      - http
      summary: Create a new volunteer
      tags:
      - volunteer
  /api/vol/get:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: |-
        This will show details of a volunteer.
        Atleast one param is required
      operationId: getVolunteer
      parameters:
      - description: Organisation ID
        in: query
        name: organisation_id
        type: string
        x-go-name: VolunteerID
      - description: Name of organisation
        in: query
        name: display_name
        type: string
        x-go-name: DisplayName
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/volResponse'
      schemes:
      - http
      summary: Get details of a volunteer
      tags:
      - volunteer
  /auth/jwt-login:
    get:
      consumes:
      - application/json
      description: Login to existing account
      operationId: JWTLogin
      parameters:
      - description: Username of user
        in: query
        name: username
        required: true
        type: string
        x-go-name: Username
      - description: Password of user
        in: query
        name: password
        required: true
        type: string
        x-go-name: Password
      responses:
        "200":
          $ref: '#/responses/JWTLoginResp'
        "401":
          $ref: '#/responses/unauthorizedError'
      schemes:
      - http
      tags:
      - auth
  /auth/jwt-refresh:
    get:
      consumes:
      - application/json
      description: Login to existing account
      operationId: JWTRefresh
      parameters:
      - in: query
        name: token
        required: true
        type: string
        x-go-name: Token
      responses:
        "200":
          $ref: '#/responses/JWTLoginResp'
        "401":
          $ref: '#/responses/unauthorizedError'
      schemes:
      - http
      tags:
      - auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login to existing account
      operationId: login
      parameters:
      - description: Username of user
        in: query
        name: username
        required: true
        type: string
        x-go-name: Username
      - description: Password of user
        in: query
        name: password
        required: true
        type: string
        x-go-name: Password
      - in: query
        name: token
        required: true
        type: string
        x-go-name: Token
      responses:
        "200":
          $ref: '#/responses/successResponse'
        "401":
          $ref: '#/responses/unauthorizedError'
      schemes:
      - http
      tags:
      - auth
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Logout from existing account
      operationId: logout
      responses:
        "200":
          $ref: '#/responses/successResponse'
      schemes:
      - http
      tags:
      - auth
produces:
- application/json
responses:
  JWTLoginResp:
    description: JWTResp response for JWT logins
    headers:
      token:
        description: Token provided after successful login
        type: string
  errResponse:
    description: ErrorResponse ...
  eventAttendeeResponse:
    schema:
      $ref: '#/definitions/EventAttendeeBridge'
  eventHostResponse:
    schema:
      $ref: '#/definitions/EventHostBridge'
  eventResponse:
    schema:
      $ref: '#/definitions/Event'
  orgResponse:
    schema:
      $ref: '#/definitions/OrgData'
  successResponse:
    description: SuccessResponse ...
  volResponse:
    schema:
      $ref: '#/definitions/VolData'
schemes:
- http
securityDefinitions:
  JWTAuth:
    description: Get token from /auth/jwt-login
    in: header
    name: Authorization
    type: apiKey
  cookieAuth:
    description: Doesnt work from swagger, head over to /login
    in: cookie
    name: SESSIONID
    type: apiKey
swagger: "2.0"
